name: Test SheetJS CDN
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  test-cdn:
    runs-on: ubuntu-latest
    steps:
      - name: Test CDN with curl
        run: |
          echo "Testing CDN access..."
          curl -f -I https://cdn.sheetjs.com/xlsx-0.20.3/xlsx-0.20.3.tgz
          
      - name: Test CDN download
        run: |
          echo "Attempting download..."
          curl -f -O https://cdn.sheetjs.com/xlsx-0.20.3/xlsx-0.20.3.tgz
          
      - name: Test npm install from CDN
        run: |
          npm install https://cdn.sheetjs.com/xlsx-0.20.3/xlsx-0.20.3.tgz

      - name: Notify Discord on failure
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -d '{"content":"CDN test failed: ${{ github.repository }} - https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
